CREATE TABLE blogful_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT,
  nickname TEXT
);

ALTER TABLE blogful_articles 
  ADD COLUMN 
    author INTEGER REFERENCES blogful_users(id) 
    ON DELETE SET NULL;

